name: Build Containerization Example

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ vars.PUBLISH_USER }}
          password: ${{ secrets.PUBLISH_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build
        run: ./gradlew build

      - name: Build Docker image
        run: docker build . -t ghcr.io/minibuildsio/artefacts/docker-ktor-containerization-example:$(./gradlew -q printVersion)

      - name: Push Docker image
        run: docker push ghcr.io/minibuildsio/artefacts/docker-ktor-containerization-example:$(./gradlew -q printVersion)
